async (page) => {
  const base='http://127.0.0.1:8765';
  const checks=[];
  const check=(condition,name)=>{if(!condition)throw new Error(name);checks.push(name);};
  await page.setViewportSize({width:1280,height:900});
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.goto(base);await page.waitForFunction(()=>window.exampleScene?.stats().meshes===5);
  const anchor=await page.locator('.anchor').boundingBox();
  for(const p of [0,.42,1,.2,1])await page.evaluate(p=>exampleMotion.sampleKinetic(p),p);
  const sampled=await page.evaluate(()=>({state:exampleMotion.getState(),opacity:getComputedStyle(document.querySelector('.word-two')).opacity}));
  check(sampled.state.progress===1&&sampled.opacity==='1','Direct and reverse kinetic sampling');
  check(JSON.stringify(anchor)===JSON.stringify(await page.locator('.anchor').boundingBox()),'Persistent anchor geometry');
  await page.locator('#kinetic-replay').click();await page.waitForTimeout(160);await page.locator('#kinetic-play').click();
  const paused=await page.evaluate(()=>exampleMotion.getState().progress);await page.waitForTimeout(150);
  check(await page.evaluate(()=>exampleMotion.getState().progress)===paused,'Explicit pause freezes playback');
  await page.evaluate(()=>{for(const hidden of [true,false]){Object.defineProperty(document,'hidden',{configurable:true,value:hidden});document.dispatchEvent(new Event('visibilitychange'));}delete document.hidden;});
  check(await page.evaluate(()=>!exampleMotion.getState().playing),'Visibility does not override explicit pause');
  await page.locator('#format').selectOption('48');await page.locator('#estimate-form button').click();
  check((await page.locator('#estimate-result').textContent()).includes('2,400'),'Truthful immediate local calculation');
  check((await page.locator('#format-identity').textContent()).includes('Journal / 48'),'Selection identity reaches result');
  await page.locator('#workflow').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/webdesign-workflow.png'});
  await page.locator('#reveal').click();await page.waitForTimeout(100);await page.locator('#reveal').click();await page.waitForTimeout(750);
  check(await page.evaluate(()=>exampleScene.stats().progress)===0,'Rapid reveal interruption returns to assembly');
  const originalPositions=await page.evaluate(()=>exampleScene.stats().positions);
  for(const p of [0,1,.4,1,0])await page.evaluate(p=>exampleScene.sampleAssembly(p),p);
  check(await page.evaluate(()=>exampleScene.stats().progress)===0,'Reverse and reassembly sampling');
  check(JSON.stringify(originalPositions)===JSON.stringify(await page.evaluate(()=>exampleScene.stats().positions)),'Canonical part transforms reassemble without drift');
  await page.locator('#spatial').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/webdesign-3d-wide.png'});
  await page.evaluate(()=>exampleScene.sampleAssembly(1));await page.screenshot({path:'/tmp/webdesign-3d-exploded.png'});
  await page.setViewportSize({width:390,height:720});await page.locator('#scene-wrap').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/webdesign-3d-narrow.png'});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Narrow viewport has no horizontal overflow');
  await page.setViewportSize({width:1000,height:450});await page.locator('#scene-wrap').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/webdesign-3d-short.png'});
  check(await page.locator('#scene canvas').count()===1,'Resize retains one renderer');
  await page.evaluate(()=>exampleScene.sampleAssembly(0));await page.locator('#reveal').click();await page.waitForTimeout(350);
  await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>exampleScene.sampleAssembly(1));await page.locator('#reveal').click();
  check(await page.evaluate(()=>exampleScene.stats().progress)===0,'Preference change and immediate reduced-motion reassembly');
  await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('#kinetic-replay').click();await page.waitForTimeout(100);await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForFunction(()=>!exampleMotion.getState().playing);
  check(await page.evaluate(()=>!exampleMotion.getState().playing),'Preference change interrupts active kinetic playback');
  await page.locator('#kinetic-replay').click();check(await page.evaluate(()=>exampleMotion.getState().progress===1&&!exampleMotion.getState().playing),'Reduced-motion static semantic state');
  await page.locator('#kinetic').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/webdesign-kinetic-reduced.png'});
  await page.evaluate(async()=>{exampleMotion.dispose();exampleMotion.mount();await exampleScene.mount();});
  check(await page.locator('#scene canvas').count()===1,'Scene and motion dispose/remount');
  await page.route('**/late-missing.gltf',async route=>{await page.waitForTimeout(100);await route.fulfill({status:404,body:'Missing fixture'});});
  await page.evaluate(async()=>{const old=exampleScene.mount('assets/late-missing.gltf');await exampleScene.mount();await old;});
  check((await page.locator('#scene-status').textContent()).includes('5 modeled parts'),'Late failed load cannot replace current scene status');
  await page.unroute('**/late-missing.gltf');
  await page.route('**/lumen.gltf?late',async route=>{await page.waitForTimeout(100);await route.continue();});
  await page.evaluate(async()=>{const old=exampleScene.mount('assets/lumen.gltf?late');await exampleScene.mount();await old;});
  check(await page.locator('#scene canvas').count()===1&&await page.evaluate(()=>exampleScene.stats().meshes===5),'Late successful load cannot populate disposed scene');
  await page.unroute('**/lumen.gltf?late');
  await page.evaluate(()=>{dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});
  await page.waitForFunction(()=>exampleScene.stats().meshes===5);
  check(await page.locator('#scene canvas').count()===1,'Persisted page lifecycle remounts the renderer');
  await page.evaluate(()=>exampleScene.mount('assets/missing.gltf'));
  check((await page.locator('#scene-status').textContent()).includes('could not load'),'Asset failure exposes semantic alternative');
  await page.evaluate(()=>exampleScene.mount());
  await page.evaluate(()=>document.querySelector('#scene canvas').dispatchEvent(new Event('webglcontextlost',{cancelable:true})));
  check((await page.locator('#scene-status').textContent()).includes('context lost'),'Context loss exposes fallback');
  await page.route('**/vendor/**',route=>route.abort());await page.reload();await page.waitForFunction(()=>document.querySelector('#scene-status').textContent.includes('3D unavailable'));
  check(await page.locator('.parts li').count()===3,'Missing renderer preserves useful HTML alternative');await page.unroute('**/vendor/**');
  await page.setViewportSize({width:1280,height:900});await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(base);
  await page.waitForFunction(()=>window.exampleMotion);await page.evaluate(()=>exampleMotion.sampleKinetic(.42));await page.screenshot({path:'/tmp/webdesign-kinetic-middle.png'});
  await page.setViewportSize({width:390,height:720});await page.locator('#kinetic').scrollIntoViewIfNeeded();await page.evaluate(()=>exampleMotion.sampleKinetic(1));await page.screenshot({path:'/tmp/webdesign-kinetic-narrow.png'});
  await page.setViewportSize({width:1000,height:450});await page.locator('.kinetic-stage').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/webdesign-kinetic-short.png'});await page.setViewportSize({width:1280,height:900});
  await page.goto(base+'/video.html');await page.locator('#synthetic').click();await page.waitForFunction(()=>document.querySelector('#video').readyState>=2);
  const metadata=await page.evaluate(async()=>{const v=document.querySelector('#video'),blob=await (await fetch(v.src)).blob();return {width:v.videoWidth,height:v.videoHeight,callback:'requestVideoFrameCallback' in v,bytes:blob.size,mime:blob.type,duration:v.duration};});
  check(metadata.width===640&&metadata.height===360,'Synthetic local clip decodes at authored dimensions');
  await page.evaluate(()=>document.querySelector('#video').play());await page.waitForTimeout(350);
  check(await page.evaluate(()=>document.querySelector('#video').currentTime>0),'Synthetic video playback advances');
  await page.evaluate(()=>{const v=document.querySelector('#video');v.pause();v.currentTime=.5;});await page.waitForTimeout(150);
  check((await page.locator('#timeline').textContent()).includes('0.50'),'Media timeline overlay follows seek');
  check(await page.evaluate(()=>document.querySelector('#video').paused),'Video pause preserved after seek');
  await page.evaluate(()=>{for(const hidden of [true,false]){Object.defineProperty(document,'hidden',{configurable:true,value:hidden});document.dispatchEvent(new Event('visibilitychange'));}delete document.hidden;});
  check(await page.evaluate(()=>document.querySelector('#video').paused),'Video visibility does not override explicit pause');
  const restored=await page.evaluate(async()=>{
    const v=document.querySelector('#video'),source=v.src;
    window.restoredVideoFrames=0;
    if(v.requestVideoFrameCallback){const original=v.requestVideoFrameCallback.bind(v);v.requestVideoFrameCallback=callback=>original((now,info)=>{window.restoredVideoFrames++;callback(now,info);});}
    dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));
    dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));
    return {sameSource:v.src===source,paused:v.paused,bytes:(await (await fetch(v.src)).blob()).size};
  });
  check(restored.sameSource&&restored.paused&&restored.bytes===metadata.bytes,'Persisted media restoration retains clip and explicit pause');
  await page.evaluate(()=>document.querySelector('#video').play());await page.waitForTimeout(250);
  check(await page.evaluate(()=>document.querySelector('#video').currentTime>.5&&(!('requestVideoFrameCallback' in document.querySelector('#video'))||window.restoredVideoFrames>0)),'Restored media playback and frame callbacks remain usable');
  await page.evaluate(()=>{const v=document.querySelector('#video');v.pause();v.currentTime=.5;});await page.waitForTimeout(100);
  await page.screenshot({path:'/tmp/webdesign-video.png'});
  await page.evaluate(async()=>{const v=document.querySelector('#video');await v.play();v.style.transform='translateY(2000px)';});await page.waitForFunction(()=>document.querySelector('#video').paused);
  check(await page.evaluate(()=>document.querySelector('#video').paused),'Offscreen media pauses without automatic resume');
  await page.evaluate(()=>{document.querySelector('#video').style.transform='';document.querySelector('#video').src='missing-video.webm';});await page.waitForFunction(()=>document.querySelector('#metadata').textContent.includes('Playback failed'));
  check((await page.locator('#metadata').textContent()).includes('static alternative'),'Media error exposes actionable fallback');
  return {checks,metadata,browser:await page.context().browser().version()};
}
